# Generated by Django 4.0.3 on 2022-04-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=5)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='files/pdfs/')),
                ('season', models.CharField(default='FA20', max_length=4)),
                ('category', models.CharField(default='OUTERWEAR', max_length=25)),
                ('comments', models.CharField(default='COMMENTS REQUIRED', max_length=5000)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='files/previews/')),
            ],
        ),
    ]
