# Generated by Django 4.0.3 on 2022-04-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.CharField(default='OUTERWEAR', max_length=25),
        ),
        migrations.AddField(
            model_name='file',
            name='season',
            field=models.CharField(default='FA20', max_length=4),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=5),
        ),
    ]
