# Generated by Django 4.0.3 on 2022-04-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_file_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
    ]
