# Generated by Django 4.0.3 on 2022-04-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_file_category_file_season_alter_file_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='comments',
            field=models.CharField(default='COMMENTS REQUIRED', max_length=5000),
        ),
    ]
