# Generated by Django 4.0.3 on 2022-04-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_file_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='files/previews/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(upload_to='files/pdfs/'),
        ),
    ]
